module.exports = [
   {
      "restaurant_name":"TEST",
      "latitude": 30.412017,
      "longitude": -97.745536,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"10.50",
      "logo":"../img/stinsons.jpg"
   },
   {
      "restaurant_name":"Stinsons",
      "description":"cafe at the beggining of the road",
      "on_burnet":true,
      "address":"4416 Burnet Rd",
      "zip":"78756",
      "latitude": 30.315252,
      "longitude": -97.741890,
      "drive_through":false,
      "service_style":"cafe",
      "phone":"512.968.4970",
      "website":"http://stinsonsbistro.com",
      "menu":"http://www.stinsonsbistro.com/menu/",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":true,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"10.50",
      "logo":"../img/stinsons.jpg"
   },
   {
      "restaurant_name":"Blue Star Cafeteria",
      "description":"across the street from pinthouse",
      "on_burnet":true,
      "address":"4800 Burnet Rd. C-300",
      "zip":"78756",
      "latitude": 30.31914,
      "longitude": -97.73964,
      "drive_through":false,
      "service_style":"cafeteria",
      "phone":"512.454.7827",
      "website":"http://bluestarcafeteria.com",
      "menu":"http://www.bluestarcafeteria.com/menus.php",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":true,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"~10",
      "logo":"../img/bluestar.gif"
   },
   {
      "restaurant_name":"Noble Sandwich Co.",
      "description":"place for pig",
      "on_burnet":true,
      "address":"4805 Burnet Rd",
      "zip":"78756",
      "latitude": 30.31899,
      "longitude": -97.73882,
      "drive_through":false,
      "service_style":"don't know yet",
      "phone":"512.666.5124",
      "website":"http://noblesandwiches.com",
      "menu":"http://noblesandwiches.com/menu",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"~10",
      "logo":""
   },
   {
      "restaurant_name":"Sonic",
      "description":"america's drive in",
      "on_burnet":true,
      "address":"4929 Burnet Rd",
      "zip":"78756",
      "latitude": 30.32083,
      "longitude": -97.73896,
      "drive_through":true,
      "service_style":"drive up fast-food",
      "phone":"512.451.7760",
      "website":"sonicdrivein.com",
      "menu":"https://www.sonicdrivein.com/menu",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"we will see",
      "logo":""
   },
   {
      "restaurant_name":"416 Bar and Grille",
      "description":"grill with a superfluous e",
      "on_burnet":true,
      "address":"5011 Burnet Rd #150",
      "zip":"78756",
      "latitude": 30.32161,
      "longitude": -97.73896,
      "drive_through":false,
      "service_style":"don't know yet",
      "phone":"512.206.0540",
      "website":"http://www.416barandgrille.com",
      "menu":"http://www.416barandgrille.com/menu/",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"10-12",
      "logo":""
   },
   {
      "restaurant_name":"Billy's on Burnet",
      "description":"Nice neighborhood bar",
      "on_burnet":false,
      "address":"2105 Hancock Dr",
      "zip":"78756",
      "latitude": 30.32199,
      "longitude": -97.73978,
      "drive_through":false,
      "service_style":"don't know yet",
      "phone":"512.407.9305",
      "website":"http://billysonburnet.com",
      "menu":"http://www.billysonburnet.com/billys-menu-0915.pdf",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"9-10",
      "logo":"../img/billys.jpg"
   },
   {
      "restaurant_name":"Chi'Lantro",
      "description":"over rated kimchi-fries",
      "on_burnet":true,
      "address":"5222 Burnet Rd",
      "zip":"78756",
      "latitude": 30.32407,
      "longitude": -97.74023,
      "drive_through":false,
      "service_style":"sit down",
      "phone":"512.852.9970",
      "website":"http://www.chilantrobbq.com",
      "menu":"http://www.chilantrobbq.com/menu/restaurant/",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"7.49",
      "logo":""
   },
   {
      "restaurant_name":"Austin Diner",
      "description":"diner",
      "on_burnet":true,
      "address":"5222 Burnet Rd",
      "zip":"78756",
      "latitude": 30.32407,
      "longitude": -97.74023,
      "drive_through":false,
      "service_style":"sit down",
      "phone":"512.467.9552",
      "website":"http://theaustindiner.com",
      "menu":"http://theaustindiner.com/index.php/menu#burgers",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":true,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"8",
      "logo":""
   },
   {
      "restaurant_name":"Hat Creek Burger Co",
      "description":"tasty treat",
      "on_burnet":true,
      "address":"5400 Burnet Rd",
      "zip":"78756",
      "latitude": 30.32843,
      "longitude": -97.73996,
      "drive_through":true,
      "service_style":"don't know yet",
      "phone":"512.452.2025",
      "website":"http://hatcreekburgers.com",
      "menu":"http://hatcreekburgers.com/menu/",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"6 (10 with combo)",
      "logo":""
   },
   {
      "restaurant_name":"ThunderCloud Subs",
      "description":"am I the only one who knows they sometimes have burgers?",
      "on_burnet":true,
      "address":"5401 Burnet Rd",
      "zip":"78756",
      "latitude": 30.32853,
      "longitude": -97.73953,
      "drive_through":true,
      "service_style":"don't know yet",
      "phone":"",
      "website":"",
      "menu":"",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"not sure yet",
      "logo":""
   },
   {
      "restaurant_name":"The Peached Tortilla",
      "description":"the peaches seldom make an appearance",
      "on_burnet":true,
      "address":"5520 Burnet Rd #100",
      "zip":"78756",
      "latitude": 30.33081,
      "longitude": -97.74022,
      "drive_through":false,
      "service_style":"sit down",
      "phone":"512.330.4439",
      "website":"http://www.thepeachedtortilla.com",
      "menu":"http://www.thepeachedtortilla.com/wp-content/uploads/2014/12/peached-dinner-menu1.pdf",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":true,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"13",
      "logo":""
   },
   {
      "restaurant_name":"Phil's Ice House",
      "description":"Ice House",
      "on_burnet":true,
      "address":"5620 Burnet Rd",
      "zip":"78756",
      "latitude": 30.33215,
      "longitude": -97.74032,
      "drive_through":false,
      "service_style":"don't know yet",
      "phone":"512.524.1212",
      "website":"http://www.philsicehouse.com",
      "menu":"http://www.philsicehouse.com/our-menu/",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":true,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"~8",
      "logo":""
   },
   {
      "restaurant_name":"Yard Bar",
      "description":"Burnet road's premier dog park",
      "on_burnet":true,
      "address":"6700 Burnet Rd",
      "zip":"78757",
      "latitude": 30.343133,
      "longitude": -97.73931,
      "drive_through":false,
      "service_style":"sit down",
      "phone":"512.900.3773",
      "website":"http://yardbar.com",
      "menu":"http://yardbar.com",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"12",
      "logo":""
   },
   {
      "restaurant_name":"Pour House",
      "description":"I miss you. (Opening back up soon)",
      "on_burnet":true,
      "address":"6701 Burnet Rd A3",
      "zip":"78757",
      "latitude": 30.34257,
      "longitude": -97.73792,
      "drive_through":false,
      "service_style":"don't know yet",
      "phone":"512.454.7687",
      "website":"http://www.pourhousepubaustin.com",
      "menu":"http://www.pourhousepubaustin.com",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"can't remember",
      "logo":""
   },
   {
      "restaurant_name":"The Frisco",
      "description":"since 1953",
      "on_burnet":true,
      "address":"6801 Burnet Rd",
      "zip":"78757",
      "latitude": 30.343795,
      "longitude": -97.738012,
      "drive_through":false,
      "service_style":"don't know yet",
      "phone":"512.459.6279",
      "website":"http://www.thefriscoaustin.com/home",
      "menu":"http://eat24hrs.com/restaurants/order2/menu.php?id=56258",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"6-10",
      "logo":""
   },
   {
      "restaurant_name":"Twisted Root Burger Co.",
      "description":"cool franchise",
      "on_burnet":true,
      "address":"7211 Burnet Rd.",
      "zip":"78757",
      "latitude": 30.347991,
      "longitude": -97.735320,
      "drive_through":false,
      "service_style":"counter service",
      "phone":"512.925.2161",
      "website":"http://twistedrootburgerco.com",
      "menu":"http://twistedrootburgerco.com/menu/",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"9-11",
      "logo":""
   },
   {
      "restaurant_name":"Top-Notch",
      "description":"classic",
      "on_burnet":true,
      "address":"7525 Burnet Rd",
      "zip":"78757",
      "latitude": 30.35114,
      "longitude": -97.73342,
      "drive_through":true,
      "service_style":"Drive up and counter service",
      "phone":"512.452.2181",
      "website":"http://topnotchaustin.com",
      "menu":"http://topnotchaustin.com/images/15TopNotchTOGO.pdf",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"~5",
      "logo":""
   },
   {
      "restaurant_name":"Bartlets",
      "description":"Houstons",
      "on_burnet":false,
      "address":"2408 W Anderson Ln",
      "zip":"78757",
      "latitude": 30.3567,
      "longitude": -97.73124,
      "drive_through":false,
      "service_style":"don't know yet",
      "phone":"512.451.7333",
      "website":"http://bartlettsaustin.com",
      "menu":"http://bartlettsaustin.com/menus/dinner",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":true,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"16-18",
      "logo":""
   },
   {
      "restaurant_name":"P. Terry's",
      "description":"goto goto",
      "on_burnet":true,
      "address":"8515 Burnet Rd",
      "zip":"78757",
      "latitude": 30.36655,
      "longitude": -97.72774,
      "drive_through":true,
      "service_style":"don't know yet",
      "phone":"512.420.9242",
      "website":"http://www.pterrys.com",
      "menu":"",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"2.35, 2.60 with fromage",
      "logo":""
   },
   {
      "restaurant_name":"Waterloo Ice House",
      "description":"Ice House",
      "on_burnet":true,
      "address":"8600 Burnet Rd",
      "zip":"78757",
      "latitude": 30.368,
      "longitude": -97.72819,
      "drive_through":false,
      "service_style":"don't know yet",
      "phone":"512.458.6544",
      "website":"http://waterlooicehouse.com",
      "menu":"http://waterlooicehouse.com/lunch-dinner",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":true,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"~10",
      "logo":""
   },
   {
      "restaurant_name":"McDonalds",
      "description":"had some cool stuff at sx",
      "on_burnet":true,
      "address":"7950 Burnet Rd",
      "zip":"78757",
      "latitude": 30.35813,
      "longitude": -97.73099,
      "drive_through":true,
      "service_style":"childhood fast-food",
      "phone":"512.454.9394",
      "website":"mcdonalds.com",
      "menu":"http://www.mcdonalds.com/us/en/food/full_menu/sandwiches.html",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"we will report",
      "logo":""
   },
   {
      "restaurant_name":"Moonie's Burger House",
      "description":"I'm excited to eat yous",
      "on_burnet":true,
      "address":"2001 Burnet Rd",
      "zip":"78758",
      "latitude": 30.40737,
      "longitude": -97.71327,
      "drive_through":false,
      "service_style":"north austin gourmet",
      "phone":"512.837.5400",
      "website":"www.mooniesburgerhouse.com",
      "menu":"http://mooniesburgerhouse.com/gracyfarms/",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "with_fries":false,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"we will see",
      "logo":""
   },
   {
      "restaurant_name":"Big Daddy's Burgers & Bar",
      "description":"you too",
      "on_burnet":false,
      "address":"9070 Research Blvd #101",
      "zip":"78758",
      "latitude": 30.37346,
      "longitude": -97.72834,
      "drive_through":false,
      "service_style":"bar",
      "phone":"512.614.0252",
      "website":"http://www.bigdaddysaustin.com",
      "menu":"http://www.bigdaddysaustin.com/menu/",
      "glankler_gripe":"no gripe yet",
      "restaurant_photo":"",
      "reviewed":false,
      "with_fries":true,
      "rating":0,
      "burgers":[
      ],
      "reviews":[
      ],
      "price":"8-9.5",
      "logo":""
   }
]
